#!/bin/bash -ue
cat > multiqc_config.yaml << EOL
# MultiQC Configuration File for RNA-Seq Pipeline

title: "RNA-Seq Analysis Report"
subtitle: "Quality Control and Processing Summary"
intro_text: "This report summarizes the quality control metrics and processing results for RNA-Seq data."

report_comment: "Generated by the Nextflow RNA-Seq Pipeline"

# Module-specific settings
fastqc_config:
    fastqc_theoretical_gc: true

# Custom plot configuration
custom_plot_config:
    fastqc_per_base_sequence_quality:
        title: "Per Base Sequence Quality"
        xlab: "Position (bp)"
        ylab: "Quality Score"
    
    fastqc_per_sequence_quality_scores:
        title: "Per Sequence Quality Scores"
        xlab: "Quality Score"
        ylab: "Count"

# Output settings
output_dir: "./results/multiqc"
make_data_dir: true
data_format: "tsv"

# Report appearance
template: "default"
EOL
